CREATE TABLE USUARIO_XXX(
ID INTEGER,
NOMBRE VARCHAR2(40),
EDAD INTEGER,
CONSTRAINT PK_ID PRIMARY KEY (ID)
)
/
CREATE OR REPLACE TRIGGER DISP_USUARIO_XXX BEFORE INSERT ON USUARIO_XXX
FOR EACH ROW 
BEGIN
IF :NEW.EDAD < 18 THEN 
RAISE_APPLICATION_ERROR(-200001,'NO TIENES MAYORIA DE EDAD');
END IF;
END;
/

-- PRUEBA DISPARADORES

INSERT INTO USUARIO_XXX VALUES(2,'ARMANDO',13);
SELECT * FROM USUARIO;

-- MODIFICAR EL DISPARADOR ANTERIOR DE TAL MANERA QUE VALIDE LO SIGUIENTE, DEBERA VERIFICAR QUE EL NOMBRE SOLO CONTENGA MAYUSCULAS, SI NO ES ASI DEBERA LANZAR LA EXCEPCION. 

 
