set serveroutput on;

CREATE TABLE ALUMNO(NUMERO_CUENTA INTEGER, NOMBRE VARCHAR2(25), PATERNO VARCHAR2(25), CONSTRAINT PK_NUMERO_CUENTA PRIMARY KEY (NUMERO_CUENTA));
CREATE TABLE MATERIA(ID_MATERIA INTEGER, NOMBRE VARCHAR2(120), CONSTRAINT PK_ID_MATERIA PRIMARY KEY (ID_MATERIA));
CREATE TABLE EVALUACION(NUMERO_CUENTA INTEGER, ID_MATERIA INTEGER, CALIFICACION FLOAT, ESTATUS CHAR,CONSTRAINT FK1_NUMERO_CUENTA foreign key (NUMERO_CUENTA) REFERENCES ALUMNO (NUMERO_CUENTA),CONSTRAINT FK2_ID_MATERIA foreign key (ID_MATERIA) REFERENCES MATERIA (ID_MATERIA));

DROP TABLE MATERIA; 
CREATE SEQUENCE SEC_MATERIA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE OR REPLACE PROCEDURE GUARDAR_MATERIA(MY_ID_MATERIA OUT INTEGER, MY_NOMBRE IN VARCHAR2)
AS
BEGIN
SELECT SEC_MATERIA.NEXTVAL INTO MY_ID_MATERIA FROM DUAL;
INSERT INTO MATERIA(ID_MATERIA,NOMBRE) VALUES(MY_ID_MATERIA,MY_NOMBRE);
END;
/

INSERT INTO ALUMNO VALUES (123,'Juan','Torres');
INSERT INTO ALUMNO VALUES (456,'Daniela','Meza');
INSERT INTO ALUMNO VALUES (789,'Armando','Cardenas');

SELECT * FROM ALUMNO;

DECLARE
VALOR INTEGER;
BEGIN
GUARDAR_MATERIA(VALOR,'Base de Datos II');
GUARDAR_MATERIA(VALOR,'Negocios Electronicos');
GUARDAR_MATERIA(VALOR,'Metodologia');
END;
/

SELECT * FROM MATERIA;

CREATE OR REPLACE TRIGGER DISP_EVALUACION BEFORE INSERT ON EVALUACION FOR EACH ROW
BEGIN 
IF :NEW.ESTATUS != 'A' || :NEW.ESTATUS != 'R' THEN
RAISE_APPLICATION_ERROR(-200001,'ERROR');
END IF;
END;
/

SELECT * FROM EVALUACION;

INSERT INTO EVALUACION VALUES (123,1,7.9,'A');
INSERT INTO EVALUACION VALUES (456,3,5,'A');
INSERT INTO EVALUACION VALUES (789,4,4.2,'R');
INSERT INTO EVALUACION VALUES (123,3,8.5,'R');

