--Practica 4


--EJERCICIO 2
--Creamos la tabla trabajador.
CREATE TABLE TRABAJADOR(SEGURO_SOCIAL INTEGER, 
                        NOMBRE  VARCHAR2(100), 
                        PATERNO VARCHAR2(100),
CONSTRAINT PK_TRABAJADOR PRIMARY KEY (SEGURO_SOCIAL));

--Creamos la secuencia para la tabla Nomina.
CREATE SEQUENCE SEC_NOMINA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE TABLE NOMINA(ID_NOMINA INTEGER,
                    SEGURO_SOCIAL INTEGER,
                    HORAS_LABORADAS INTEGER,
                    FECHA_PAGO DATE,
                    SALDO FLOAT,
CONSTRAINT PK_ID_NOMINA PRIMARY KEY (ID_NOMINA), 
CONSTRAINT FK_SEGURO_SOCIAL FOREIGN KEY (SEGURO_SOCIAL));


--Procedimiento para guardar trabajadores.

CREATE OR REPLACE PROCEDURE GUARDAR_TRABAJADOR(MY_ID IN INTEGER, MY_NOMBRE IN VARCHAR2, MY_PATERNO IN VARCHAR2)
AS
BEGIN
INSERT INTO TRABAJADOR VALUES(MY_ID, MY_NOMBRE, MY_PATERNO);
END;
/

CREATE OR REPLACE PROCEDURE GUARDAR_NOMINA(MY_ID_NOMINA OUT INTEGER, MY_SEGURO_SOCIAL IN INTEGER)
AS
BEGIN
SELECT SEC_NOMINA.NEXTVAL INTO MY_ID_NOMINA FROM DUAL;
INSERT INTO NOMINA(ID_NOMINA,SEGURO_SOCIAL) VALUES(MY_ID_NOMINA,MY_SEGURO_SOCIAL);
END;
/

--Guardar los siguientes dos trabajadores con su nomina.

declare
VALOR INTEGER;
BEGIN
--GUARDAR_TRABAJADORES(333,'JUAN','CAMPOS');
GUARDAR_NOMINA(VALOR, 333);
END;
/

declare
VALOR INTEGER;
BEGIN
--GUARDAR_TRABAJADORES(777,'ANA','LOPEZ');
GUARDAR_NOMINA(VALOR,777)
END;
/
-- ---------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TRABAJADOR; 
SELECT * FROM NOMINA; 
