SET SERVEROUTPUT ON;
-- contar y copiar
CREATE TABLE USUARIO_INICIAL(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(20));
CREATE TABLE RESPALDO_USUARIOINICIAL(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(20));

CREATE OR REPLACE PROCEDURE CONTAR(NUMERO OUT INTEGER) 
AS
BEGIN 
SELECT COUNT (*) INTO NUMERO FROM USUARIO_INICIAL;
DBMS_OUTPUT.PUT_LINE('ENCONTRADOS' || NUMERO);
END;
/

DECLARE 
VALOR INTEGER
BEGIN
CONTAR(VALOR);
END;
/

--COPIA

CREATE OR REPLACE PROCEDURE COPIAR 
AS
CURSOR CUR_USUARIO_INICIAL IS SELECT * FROM USUARIO_INICIAL;
BEGIN 
FOR REC IN CUR_USUARIO_INICIAL LOOP
INSERT INTO RESPALDO_USUARIOINICIAL
END;
/

CREATE OR REPLACE TRIGGER DISP_USUARIO_INICIAL
BEFORE INSERT ON USUARIO_INICIAL FOR EACH ROW
DECLARE
VALOR INTEGER;
BEGIN
CONTAR(VALOR);
IF VALOR=3 THEN 
COPIAR();
DELETE FROM USUARIO_INICIAL;
END;
/






